### ISSUE TITLE
Eggs missing?

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#110]
I realized some eggs are mysteriously (for me) missing. One example is 20/022 by @invemichele 

The source seems correct:
https://github.com/plumed-nest/plumed-nest/blob/master/eggs/20/022/nest.yml

The Action built it (this is copied and pasted from [build job n. 4](https://github.com/plumed-nest/plumed-nest/actions/runs/4072613676/jobs/7015569478)):
```
eggs/20/022/ {'url': 'https://github.com/invemichele/OPESexpanded/archive/master.zip', 'pname': 'Unified Approach to Enhanced Sampling', 'category': 'methods', 'keyw': 'OPES, expanded ensembles, importance sampling', 'plumed_version': '2.8', 'contributor': 'Michele Invernizzi', 'doi': '10.1103/PhysRevX.10.041034', 'history': {'2020-07-14': 'original submission', '2020-11-17': 'moved to v2.8 and added doi'}, 'instructions': 'Perform replica-exchange-like sampling using a bias-potential method based on collective variables. Using OPES allows for fast convergence and requires extremely few external parameters. Only post-processing required is a simple umbrella-sampling reweighting.  More information on the method can be found [here](https://www.plumed.org/doc-master/user-doc/html/_o_p_e_s.html). \n', 'ref': '', 'ref_url': ''}
```

The [artefact](https://github.com/plumed-nest/plumed-nest/actions/runs/4072613676) does not contain it:
```
- id: '20.032'
  name: 'Modeling the thermodynamics of conformational isomerism in solution via unsupervised clustering, the case of Sildenafil'
  shortname: 'Modeling the th...'
  category: materials
  keywords: clustering, conformational isomers
  shortkeywords: clustering, conformationa...
  contributor: Matteo Salvalaglio
  doi: 10.1021/acs.jcim.0c01387
  path: eggs/20/032/
  reference: 'V. Marinova, L. Dodd, S.-J. Lee, G. P. F. Wood, I. Marziano, M. Salvalaglio, Identifying Conformational Isomers of Organic Molecules in Solution via Unsupervised Clustering. Journal of Chemical Information and Modeling. 61, 2263–2273 (2021)'
  ref_url: 'http://dx.doi.org/10.1021/acs.jcim.0c01387'
  ninputs: 20
  nfail: 0
  nfailm: 0
  preprint: 0
- id: '20.012'
  name: 'Combining Machine Learning and Enhanced Sampling Techniques for Efficient and Accurate Calculation of Absolute Binding Free Energies'
  shortname: 'Combining Machi...'
  category: bio
  keywords: metadynamics, well-tempered ensemble, ligand binding, binding affinity calculations, novel COLVAR, funnel restraints, Hamiltonian replica-exchange, PathCV, COMetPath, SWISH
  shortkeywords: metadynamics, well-temper...
  contributor: Francesco Gervasio
  doi: 10.1021/acs.jctc.0c00075
  path: eggs/20/012/
  reference: 'R. Evans, L. Hovan, G. A. Tribello, B. P. Cossins, C. Estarellas, F. L. Gervasio, Combining Machine Learning and Enhanced Sampling Techniques for Efficient and Accurate Calculation of Absolute Binding Free Energies. Journal of Chemical Theory and Computation. 16, 4641–4654 (2020)'
  ref_url: 'http://dx.doi.org/10.1021/acs.jctc.0c00075'
  ninputs: 3
  nfail: 0
  nfailm: 0
  preprint: 0
```

Any idea?

**Comment by maxbonomi** [comment]
Have you tried rebuilding the nest and see if the error is still there?Sent from my iPhoneOn 2 Feb 2023, at 14:13, Giovanni ***@***.***> wrote:﻿
I realized some eggs are mysteriously (for me) missing. One example is 20/022 by @invemichele
The source seems correct:
https://github.com/plumed-nest/plumed-nest/blob/master/eggs/20/022/nest.yml
The Action built it (this is copied and pasted from build job n. 4):
eggs/20/022/ {'url': 'https://github.com/invemichele/OPESexpanded/archive/master.zip', 'pname': 'Unified Approach to Enhanced Sampling', 'category': 'methods', 'keyw': 'OPES, expanded ensembles, importance sampling', 'plumed_version': '2.8', 'contributor': 'Michele Invernizzi', 'doi': '10.1103/PhysRevX.10.041034', 'history': {'2020-07-14': 'original submission', '2020-11-17': 'moved to v2.8 and added doi'}, 'instructions': 'Perform replica-exchange-like sampling using a bias-potential method based on collective variables. Using OPES allows for fast convergence and requires extremely few external parameters. Only post-processing required is a simple umbrella-sampling reweighting.  More information on the method can be found [here](https://www.plumed.org/doc-master/user-doc/html/_o_p_e_s.html). \n', 'ref': '', 'ref_url': ''}

The artefact does not contain it:
- id: '20.032'
  name: 'Modeling the thermodynamics of conformational isomerism in solution via unsupervised clustering, the case of Sildenafil'
  shortname: 'Modeling the th...'
  category: materials
  keywords: clustering, conformational isomers
  shortkeywords: clustering, conformationa...
  contributor: Matteo Salvalaglio
  doi: 10.1021/acs.jcim.0c01387
  path: eggs/20/032/
  reference: 'V. Marinova, L. Dodd, S.-J. Lee, G. P. F. Wood, I. Marziano, M. Salvalaglio, Identifying Conformational Isomers of Organic Molecules in Solution via Unsupervised Clustering. Journal of Chemical Information and Modeling. 61, 2263–2273 (2021)'
  ref_url: 'http://dx.doi.org/10.1021/acs.jcim.0c01387'
  ninputs: 20
  nfail: 0
  nfailm: 0
  preprint: 0
- id: '20.012'
  name: 'Combining Machine Learning and Enhanced Sampling Techniques for Efficient and Accurate Calculation of Absolute Binding Free Energies'
  shortname: 'Combining Machi...'
  category: bio
  keywords: metadynamics, well-tempered ensemble, ligand binding, binding affinity calculations, novel COLVAR, funnel restraints, Hamiltonian replica-exchange, PathCV, COMetPath, SWISH
  shortkeywords: metadynamics, well-temper...
  contributor: Francesco Gervasio
  doi: 10.1021/acs.jctc.0c00075
  path: eggs/20/012/
  reference: 'R. Evans, L. Hovan, G. A. Tribello, B. P. Cossins, C. Estarellas, F. L. Gervasio, Combining Machine Learning and Enhanced Sampling Techniques for Efficient and Accurate Calculation of Absolute Binding Free Energies. Journal of Chemical Theory and Computation. 16, 4641–4654 (2020)'
  ref_url: 'http://dx.doi.org/10.1021/acs.jctc.0c00075'
  ninputs: 3
  nfail: 0
  nfailm: 0
  preprint: 0

Any idea?

**Comment by GiovanniBussi** [comment]
Fixed by rerunning... No idea why
