### ISSUE TITLE
submitted is considered a doi in browse.md

### ISSUE THREAD

**Issue by carlocamilloni** [plumed-nest/plumed-nest#32]
The generated table does not check for submitted/unpublished

**Comment by maxbonomi** [comment]
I actually left it that way because I liked the consistency (color, underlined) with the rest of the table.
But we can change to appear as in the project page

**Comment by carlocamilloni** [comment]
Yes the problem is that you can click it and then you get an error from the doi website

**Comment by maxbonomi** [comment]
Ok, we can just put “submitted/unpublished” with no links at all
