### ISSUE TITLE
name for Project ID

### ISSUE THREAD

**Issue by maxbonomi** [plumed-nest/plumed-nest#34]
I think we should decide for a name for the project IDs. Options mentioned so far
* plumeDnest:19.001
* egg:19.001
* plumEgg:19.001

Other ideas?

**Comment by maxbonomi** [comment]
Well, in the meantime I vote for plumEgg

**Comment by carlocamilloni** [comment]
I agree with plumEgg,
But actually I am bit worried of taking this a bit too far, so maybe plumXiv could be more standard

C

**Comment by maxbonomi** [comment]
I see. Maybe

plumID

is more neutral?

**Comment by carlocamilloni** [comment]
Yes I am more for plumid 

Sent from my iPhone

**Comment by GiovanniBussi** [comment]
I also would use that. Something like

plumID:19.000

or

plumId:19.000

plumid:19.000 looks like a single word

Giovanni

**Comment by maxbonomi** [comment]
I would prefer plumID, it helps to have two letters in upper-case, otherwise in 

plumId 

people might not understand if it is a capital "i" or lowercase "elle". PLUMED is already difficult to pronounce, let's make this as easy as possible ;-)

**Comment by maxbonomi** [comment]
I will close this, but if Gareth has concerns about the name, happy to re-open it
