### ISSUE TITLE
Plumed nest badge? 

### ISSUE THREAD

**Issue by spiwokv** [plumed-nest/plumed-nest#36]
What about some Plumed nest badge, similar to the one for Travis-CI - passed/errored? Travis-CI badges are SVG files, so in fact text files. Example:

https://github.com/spiwokv/plumed_nest_by_spiwokv/blob/master/badge.svg

**Comment by maxbonomi** [comment]
I don’t see anything :-(

**Comment by spiwokv** [comment]
Sorry, I did some editing of the post. Here is the image:
https://github.com/spiwokv/plumed_nest_by_spiwokv/blob/master/badge.svg
here is the text:
https://raw.githubusercontent.com/spiwokv/plumed_nest_by_spiwokv/master/badge.svg

**Comment by spiwokv** [comment]
Finally:
<img src="https://raw.githubusercontent.com/spiwokv/plumed_nest_by_spiwokv/master/badge.svg?sanitize=true">
https://raw.githubusercontent.com/spiwokv/plumed_nest_by_spiwokv/master/badge.svg?sanitize=true

**Comment by maxbonomi** [comment]
I like that!
I was thinking were we could put it...

**Comment by spiwokv** [comment]
I will try to fork the plumed-nest.github.io, put it there and make a pull request. I don't know how plumed-nest and plumed-nest.github.io are consolidated together, so maybe you have to copy somethink from one repo to another.

**Comment by maxbonomi** [comment]
we do not submit directly to plumed-nest.github.io, but only to plumed-nest.
For the moment, we are still discussing about the name for Project IDs, so we might change soon "plumEgg" into something different ;-)

**Comment by spiwokv** [comment]
Probably I need to fork plumed-nest.github.io to try if it works, I need GitHub web. So I will fork, try and if works I would let you know, rather than making a pull request.

**Comment by spiwokv** [comment]
https://spiwokv.github.io/plumed-nest/eggs-19/008/badge.svg

I can try to change the color depending on whether all Travis-CI runs passed or not, but as far as I understand, at the moment nest does not retrieve this information, only shows badges.

**Comment by spiwokv** [comment]
https://spiwokv.github.io/plumed-nest/eggs-19/008/badge.svg

So now it is red for failed and blue for passed, chose other colors if you like the badge. Design changes are also welcome.

**Comment by maxbonomi** [comment]
I think for the gree/red badges in the table we need ti show the badge related to the specific version if plumed tested. Bit ai like the neutral badge, just thinking where we could put it

**Comment by spiwokv** [comment]
I understand that failure of some tests does not necessarily mean that the egg is rotten, I will make a neutral badge with some colour from the gradient on the web front page. Or you can pick the colour:
https://www.w3schools.com/colors/colors_picker.asp
I would put it into README.md of each project. This means that contributors can link it easily.

**Comment by spiwokv** [comment]
The colour right bellow the nest in the front page is #157779.

**Comment by carlocamilloni** [comment]
The badge is now included in the test site. I like it and I would also merge it to master soon

**Comment by spiwokv** [comment]
I will try to make some better link (to show Markdown and HTML code to include the badge).

**Comment by spiwokv** [comment]
I added this: https://github.com/plumed-nest/plumed-nest/pull/55
see here: https://spiwokv.github.io/plumed-nest-test/eggs-19/006/
click to the badge

**Comment by carlocamilloni** [comment]
I added it to my webpage
https://sites.unimi.it/camilloni/index.php/publications/

**Comment by spiwokv** [comment]
I just found that it points to the test site. I will fix it tonight and @carlocamilloni will have to fix it in his web

**Comment by spiwokv** [comment]
Both, there is a different order of hypertext and image links in Markdown and HTML
