### ISSUE TITLE
Problems with INCLUDE statement

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#4]
When using `INCLUDE` statements, the included file is not actually processed to html (unless it is by chance called `plumed*.dat` as well I guess).

**Comment by carlocamilloni** [comment]
I have added now a case where the plumed input files use the INCLUDE statement.  Here I am explicitly listing all of them, but only some pass the validation because other requires informations from the others. 
https://www.plumed-nest.org/eggs-19/012/
Furthermore this is a case that fails because to work would needs to know the exact number of atoms

**Comment by GiovanniBussi** [comment]
My plan was to fix the issue in this way:
- User should only point to "master" files (not to the included one). Equivalently, the master files should be the only ones named `plumed*dat`. In this way only master files will be tested by driver.
- When converting the files to highlight syntax, I would take note of all `INCLUDE`d files. I will additionally convert those included files to md (or html). In the `INCLUDE FILE=xx` statement, `xx` will be a link to the file.

Would that be ok?

About the number of atoms, which is the input file that require the number of atoms to be known?

**Comment by carlocamilloni** [comment]
> On 17 Apr 2019, at 17:40, Giovanni <notifications@github.com> wrote:
> 
> My plan was to fix the issue in this way:
> 
> User should only point to "master" files (not to the included one). Equivalently, the master files should be the only ones named plumed*dat. In this way only master files will be tested by driver.
This can work using the input file list instead than renaming file


> When converting the files to highlight syntax, I would take note of all INCLUDEd files. I will additionally convert those included files to md (or html). In the INCLUDE FILE=xx statement, xx will be a link to the file.


> Would that be ok?
> 
yes
> About the number of atoms, which is the input file that require the number of atoms to be known?
> 
The plumed-saxsCG.dat because we map the virtual atoms defined in plumed-beads.dat to the MOLINFO pdb file
