### ISSUE TITLE
fetch data directly from subdirectories of GitHub reps

### ISSUE THREAD

**Issue by maxbonomi** [plumed-nest/plumed-nest#43]
how difficult would it be to have a special "path" which is not a zip archive but a subdirectory of a Github archive?

**Comment by GiovanniBussi** [comment]
You want to really avoid downloading the full repo or is it ok to download and then discard? I think the first option is not possible (at least, I don't know how)

**Comment by maxbonomi** [comment]
One collaborator has in one repo multiple projects (in different directories), that will end up as separate projects in the nest
I would like to be able to fetch one particular subfolder. But also download everything and them discard (not test) things not
specified in plumed_input would be ok for me.

**Comment by GiovanniBussi** [comment]
If you provide the list of plumed_input files it should already work. We could add an option to choose the root dir within the zip file. It could be something like:

````
url: path/to/zip
rootdir: path/to/root
````
If unset we discover it as we do now. This will make it easy to work relative to a subdirectory.

However, notice that downloading multiple times the same zip is very inefficient. I would suggest making a separate repository where you just store the zip files or a separate repository per project.

**Comment by maxbonomi** [comment]
This is the problem(s):
- each individual zip file would be over 100MB - not allowed on Github.
- Downloading the entire Github archive for each test would take too long
- the collaborator prefers having a single GitHub archive for all projects

**Comment by GiovanniBussi** [comment]
Notice that each repository is limited to 1 Gb, so that your collaborator is limited to 10 projects (if each is 100Mb). I am not sure using a single GitHub repository is the best way to store this kind of material. I would use one GitHub repo per project and perhaps a single repo with either links (or submodules) as an index.

Maybe [here](https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo) you can find some idea. But if what happens is that, remotely, GitHub has to repack files and takes a lot of time then I would prefer not to use it.

**Comment by maxbonomi** [comment]
Did not know that.
Yes, then it’s better to have one repo per project

**Comment by GiovanniBussi** [comment]
Actually I see that most of the eggs refer to individual zip files contained in github repositories
````
git grep url: | grep github | grep raw | wc -l
002/nest.yml:url: https://github.com/maxbonomi/plumed-nest-data/raw/master/projects-2018/EMMI-STRA6.zip 
003/nest.yml:url: https://github.com/maxbonomi/plumed-nest-data/raw/master/projects-2018/EMMI-ClpP.zip 
004/nest.yml:url: https://github.com/maxbonomi/plumed-nest-data/raw/master/projects-2016/MI-UBQ.zip
005/nest.yml:url: https://github.com/maxbonomi/plumed-nest-data/raw/master/projects-2017/cmyc.zip 
007/nest.yml:url: https://github.com/maxbonomi/plumed-nest-data/raw/master/projects-2019/EMMI-MT.zip
008/nest.yml:url: https://github.com/spiwokv/plumed_nest_by_spiwokv/raw/master/anncolvar.zip
010/nest.yml:url: https://github.com/carlocamilloni/papers-data/raw/master/zip-for-nest/2018/weber2018_LC.zip 
012/nest.yml:url: https://github.com/carlocamilloni/papers-data/raw/master/zip-for-nest/2019/paissoni19iucr.zip 
014/nest.yml:url: https://github.com/mme-ucl/plumed-nest-data/raw/master/mil-101_paper_setup.zip 
015/nest.yml:url: https://github.com/mme-ucl/plumed-nest-data/raw/master/Ibuprofen_conformers_JCTC.zip 
016/nest.yml:url: https://github.com/mme-ucl/plumed-nest-data/raw/master/succinnic_acid_input_files.zip 
017/nest.yml:url: https://github.com/riccardocapelli/papers_data/raw/master/pathway_search2019/input_data.zip 
````
A few are using zip files made by github
````
git grep url: | grep github | grep archive
001/nest.yml:url: https://github.com/srnas/shape-md/archive/476e47196772e5dc109018bc4c2447c5dc234381.zip
009/nest.yml:url: https://github.com/srnas/tetraloops-trajectories/archive/d54b27a82ab828f4f7a2c168c2c8c8f02d08ce09.zip
013/nest.yml:url: https://github.com/bussilab/ff-fitting-tools/archive/master.zip
````
and the remaining two are from materialscloud
````
git grep url: | grep materi
000/nest.yml:url: https://archive.materialscloud.org/file/2019.0004/v2/inputs.zip
006/nest.yml:url: https://archive.materialscloud.org/file/2019.0013/v1/flyinggaussian2.zip
````

Of course the only relevant thing is that nest sitters can access the zip files. However, I think that using a full repository is much simpler, and has the advantage that a reader can directly "browse the zip file" simply going to the corresponding github page (without downloading it). At the price that you have an extra repository per paper, which for me is something I always did anyway (e.g., to give proper write access to the co-authors, among other reasons).

**Comment by maxbonomi** [comment]
I suggested to the collaborator to keep one repository per paper, mostly for reasons of space. Also I guess it is also easier to store old versions if you have all the files not compressed in a single archive....
