### ISSUE TITLE
Issues with materialscloud

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#50]
It looks like materialscloud archive is down. This command never returns:
````
wget https://archive.materialscloud.org/file/2019.0013/v1/flyinggaussian2.zip
````
and the nest.py gives a timeout error at that egg. I think we should implement some caching and store the content of the eggs directories so that if they cannot be reconstructed we use the previous ones.

I removed the three problematic eggs. To restore them it will be sufficient to use `git revert 761c3280fdf9421903afd3adffd638ec66ae688e`.

@spiwokv @invemichele

**Comment by invemichele** [comment]
Yes, their website is working but the archive is not reachable. I wrote them about it, will let you know if I have any news.

**Comment by spiwokv** [comment]
It links to: https://object.cscs.ch/v1/AUTH_b1d80408b3d340d... so there must be some problem with some CSCS cloud.

**Comment by invemichele** [comment]
It's back online
