### ISSUE TITLE
display long PLUMED input file names in project table

### ISSUE THREAD

**Issue by maxbonomi** [plumed-nest/plumed-nest#52]
Look at these:

https://www.plumed-nest.org/eggs-19/021/

To me the table looks quite ugly. I would re-insert short names for the PLUMED input files, if you are all ok with that! @GiovanniBussi

**Comment by carlocamilloni** [comment]
Yes

Sent from my iPhone

**Comment by GiovanniBussi** [comment]
Here the most interesting part is the end of the name.. should we use

....restofthename.dat

Perhaps? I don’t know how general it is.

Alternatively, if you replace all “/“ with “/ “ so that they are wrapped on multiple lines maybe it would look better?

**Comment by maxbonomi** [comment]
I tried the first option, it looks good now I think
