### ISSUE TITLE
Move eggs to a single directory

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#59]
I think in order to implement #24 we will need all eggs in a single directory. Perhaps it is better to change `eggs-19` to `eggs/19` before people start using the badge #36

**Comment by maxbonomi** [comment]
I am ok with this!

**Comment by carlocamilloni** [comment]
Also ok! (I am already using the badge :-) )

**Comment by spiwokv** [comment]
I need to correct the badge to point to the production, not test site.
