### ISSUE TITLE
additional software

### ISSUE THREAD

**Issue by maxbonomi** [plumed-nest/plumed-nest#6]
Should we ask the specification of the additional software used (and the exact version) in the Instructions form or as a separate form?

**Comment by GiovanniBussi** [comment]
Is the additional software something that we are supposed to run on Travis-CI as well?

I would prefer not, otherwise this will add a lot of complexity.

If the answer is not, we will never need this information to be parsed, so I think having it in Instructions would be sufficient.

**Comment by maxbonomi** [comment]
No, not to run it on Travis-CI. I think we need to communicate this information to the public for the sake of reproducibility of the examples. The zip archive contains all the data to re-rerun the simulation. On our hand we check only the PLUMED input files, but I think knowing which versions of the other codes have been used is important.

**Comment by GiovanniBussi** [comment]
I see but then the zoology of possible information is very large. I think it might be difficult to make meaningful categories. I would leave it as free form, and in this case it should fit naturally in instructions. What do you think?

**Comment by maxbonomi** [comment]
I agree. I will add a comment to the Instructions form and/or an example as a placeholder

**Comment by maxbonomi** [comment]
Added some info, still I would love to make the column where the forms are a bit wider. Did not have much success, mostly because I am not an expert with CSS.
