### ISSUE TITLE
Adding yellow badge

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#66]
This is related to #65 and other discussions we had in the last week.

A possible improvement could be:
- Allow a field `modified_version: true` in the yml file, either global or per input (same as `nreplicas` and `natoms`).
- For any test that fails, if the corresponding `modified_version` field is true, make the badge yellow rather than red.

This would allow people to quickly see what is working with the official version (green), what requires some special version otherwise would not run (yellow), and what is failing, possibly because it is not maintained or the official code changed (red).

Alternatively, the inputs requiring a modified versions could be made always yellow (irrespectively of the result). The advantages would be:
1. It is clearer that they need a modified version (it could be that the official code can read the input but does not work correctly)
2. It motivates people to contribute to the official code in order to allow their flags to become green.

What do you think?

**Comment by spiwokv** [comment]
I can try if there is an agreement.

**Comment by GiovanniBussi** [comment]
@spiwokv just to make clear that I am referring to the badges for individual inputs, not to those for the whole egg.

**Comment by spiwokv** [comment]
I see

**Comment by maxbonomi** [comment]
I like this!
I would prefer the option always yellow for modified versions!

**Comment by carlocamilloni** [comment]
I agree with Max

**Comment by GiovanniBussi** [comment]
As proposed by @carlocamilloni we might use special strings for `plumed_version` rather than adding a new field. Could be anything matching `*-mod` to imply that the version is customized.

**Comment by invemichele** [comment]
What about small modifications, such as just adding one .cpp file? 
Maybe it would be nice to encourage people to use the `LOAD` keyword, so that the input works on the current plumed version.

But in my case the input was still failing on travis due to some obscure `std::bad_alloc`, even though on my computer it was working properly...

**Comment by maxbonomi** [comment]
As Giovanni pointed out, it might be a problem of memory limitations of travis.
In this case, maybe it is enough to add a warning in the Instructions section.

Max

**Comment by carlocamilloni** [comment]
I mean sharing cpp files with LOAD is perfectly ok and we should encourge it but at the same time it should be clear if a code is officially distributed or not. Personally I really dislike sentences like (this is not your case) that the code can be requested to the authors. This is the opposite of the philosophy of the nest.

**Comment by GiovanniBussi** [comment]
Eggs with LOAD should in principle result in green badges, since the input
is "runnable" (we cannot say "reproducible" since we do not test the
output).

I think the .cpp code included should be considered as part of the input
file, although perhaps less portable across multiple plumed versions.

**Comment by carlocamilloni** [comment]
I agree but plumed_version should mention the -mod I think to stress that additional cpp files are needed.

**Comment by GiovanniBussi** [comment]
If the additional files are in the zip they are "as addition as the input
file" no?

The point is that anyone would be able to run them out of the box using the
provided files.

**Comment by invemichele** [comment]
so if runnable -> green badge, if fails and -mod -> yellow, if fails and no -mod -> red

**Comment by carlocamilloni** [comment]
Yes but -mod also implies that if something does not work this is not necessarily related to the plumed official distribution.
The loaded cpp files manual is not going to be available on the web etc

**Comment by GiovanniBussi** [comment]
This is fixed now I think. You can see an example [here](https://www.plumed-nest.org/test-site/eggs/19/050/) and [here](https://github.com/plumed-nest/plumed-nest/blob/test/eggs/19/050/nest.yml), should be visible until someone else force pushes the test branch.

I will not merge the egg (it was a random test).

**Comment by GiovanniBussi** [comment]
@carlocamilloni this also applies to input files. How do you distinguish a
`Puckering.cpp` from an implementation computing puckering coordinates using `MATHEVAL`?

**Comment by maxbonomi** [comment]
Super cool

**Comment by carlocamilloni** [comment]
The difference is that they are both supported by us so a segfault or a lack of documentation is related to the distributed version.
I mean I am fine to have the green badge if it is runnable I only think that if to work on needs more code this should be somehow made as clear as possible

**Comment by GiovanniBussi** [comment]
(closed in the sense that this is implemented but still we have the open issue of deciding what to do with eggs including LOAD)

**Comment by maxbonomi** [comment]
If we want to use the coloring scheme to encourage/motivate people to contribute back to master
independent pieces of codes, maybe we should mark as yellow also those eggs that work
with LOAD.
