### ISSUE TITLE
Color of the egg badge

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#67]
@spiwokv @plumed/all perhaps we could think about changing the color of the badge made by Vojtech?

One possibility would be to make it red in extreme cases (e.g. the zip is not available - currently this crashes the whole site but I think should be fixed).

Alternatively we could have different colors based on some average color of the single input badges (#66), but I am not sure it is worth.

**Comment by spiwokv** [comment]
average color is possible

**Comment by maxbonomi** [comment]
If the badge is used on our personal website just as a link to the project page,
I am not sure if useful to have it colored by “quality” there

**Comment by GiovanniBussi** [comment]
It's pretty standard to color these badges (for instance, travis badges are colored depending on the state of the build).

Anyway, my preference would be to only make them red if building the egg-related page fails. This would warn readers that the egg itself is not accessible anymore. In all other cases they could be blue as they are now.

**Comment by maxbonomi** [comment]
Ok for this binary classification then!

**Comment by GiovanniBussi** [comment]
currently there is no way to have a red badge actually since if one zip misses the whole build is broken... We will need to add some check

**Comment by spiwokv** [comment]
There is a similar problem for regular software testing with Travis. It happened to me several times that some library was not available to download which resulted to failed badge by Travis. Should I try to make bi-color or gradient badges (color to be weighted by number of passes vs. fails)?

**Comment by GiovanniBussi** [comment]
@spiwokv I am not sure it is worth. The additional complication would be that we would have to save the state between builds (now we are always force pushing the website) in order to do this averaging. One thing we discussed is that when an egg cannot be built we could render the previous version. This will require some work anyway.
