### ISSUE TITLE
using plumed driver --natoms

### ISSUE THREAD

**Issue by maxbonomi** [plumed-nest/plumed-nest#7]
Most of the examples I would like to upload require reading a pdb file to assign some atoms-specific properties. In this case --natoms should be equal to the actual number of atoms used in my simulation. I think Carlo will have similar problems.

**Comment by maxbonomi** [comment]
This actually seems to working, so I don't think it will be a problem for me. What about you @carlocamilloni ?

**Comment by carlocamilloni** [comment]
this is a case that fails because to work would needs to know the exact number of atoms. 
https://www.plumed-nest.org/eggs-19/012/

**Comment by carlocamilloni** [comment]
I added the possibility to list the exact number of atoms, cf https://www.plumed-nest.org/eggs-19/012/. This makes these test to work correctly. Currently this is an advanced feature, that is that the user must add the field by hand
