### ISSUE TITLE
Rules for yellow badge

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#70]
See #66 
Currently implemented:
- *-mod version will always give a yellow badge
- other version will give a green/red badge

Notice that the yellow badge overrides both "latest stable" and "master" badges.

Also notice that @carlocamilloni would prefer to have mark in some way eggs that compiles on-the-fly alien code (with `LOAD`), to be discussed.

**Comment by maxbonomi** [comment]
Do we have examples of input files that now work with LOAD?
I found another example

https://www.plumed-nest.org/eggs/19/026/

that might work if 3 additional .cpp files (included in the zip) are loaded.

Max

**Comment by GiovanniBussi** [comment]
I think you should ask @gcsosso to add commands such as
````
LOAD FILE=../path/../first.cpp
LOAD FILE=../path/../second.cpp
````
at the beginning of the `plumed.dat` file.

It should work in principle...

**Comment by maxbonomi** [comment]
Sent an email 10 min ago ;-)

**Comment by maxbonomi** [comment]
Also to Bernd. He has two eggs which require an additional cpp file

**Comment by GiovanniBussi** [comment]
I indeed insist that the green badge should be the prize for those who share the code rather then making it available upon request :-)

If you want to distinguish those using LOAD we can define a new color in between yellow and green. Actually the current yellow is not very nice (looks more like orange)

**Comment by maxbonomi** [comment]
I fully agree!
I think we can leave it yellow-ish for both input files that need additional files to work
(but they are provided in the zip file and LOADed) and those for which the source code is not available.
The (subtle) difference is when you click on the yellow badge: in the former case you see no errors, in the latter yes.
Or we can make the difference more explicit

**Comment by GiovanniBussi** [comment]
I fully disagree :-)

With "sharing the code" I meant "including it in the zip file".

I actually do not check the code in contributed modules more than the one in these zip files. The only difference is that code in contributed modules should pass regtests (but we have no hard constraint on the existence of those tests) and should pass our scripts checking C++ syntax.

**Comment by maxbonomi** [comment]
;-)
yes, but we should motivate people to contribute back to PLUMED rather than share orphan files.
An the prize for this “giving back” should be the green badge of honor

**Comment by invemichele** [comment]
just a suggestion...
maybe a simple solution could be to keep red and green badges only for "running" or "not running" (regardless of LOAD) and put an extra yellow custom flag somewhere else

**Comment by maxbonomi** [comment]
Actually, you are right. This information should not be in the right part of the badge (failed/pass = red/green),
but on the left part of it (v2.5/master). Maybe we could color that in yellow if needed a custom version.

**Comment by GiovanniBussi** [comment]
Yellow (left) badge with LOAD is on the test-site:
https://www.plumed-nest.org/test-site/eggs/19/000/
I actually don't like it very much.

I will now implement the removal of the badge for 2.5 when declared version is 2.6.

**Comment by invemichele** [comment]
what about adding instead an extra yellow badge with the word "custom" or "modded" on the right of the other badges?
with maybe a simple explanation of its meaning if one clicks on it

**Comment by GiovanniBussi** [comment]
I would like that more indeed.

**Comment by maxbonomi** [comment]
You mean a separate badge or a third ‘panel’? In the latter case, I would add it right of the official version, with pass/failed further right

**Comment by maxbonomi** [comment]
On another note, if I am using a modified version of the latest release, should I declare it 2.6 or something else? It is a bit weird to declare a version that it does not exist yet

**Comment by GiovanniBussi** [comment]
I don't think a third panel is available. I would add a further badge with
something like
(code|LOAD) (perhaps linked to the LOAD manual page?)
or
(code|custom)

I would actually make custom red and load yellow, since to me it is way
better if the code is provided with the zip file.

(actually, I personally would make the LOAD badge green or even avoid it
completely, and only notify for custom code).

**Comment by GiovanniBussi** [comment]
Should be 2.6-mod if it is based on master and 2.5-mod if it is based on
2.5.

I think we have to call "master" as "2.6" otherwise we will have to update
all the eggs at every new major release

**Comment by maxbonomi** [comment]
Ok, this would be consistent with what is actually printed in the plumed log file. I like that

**Comment by maxbonomi** [comment]
I have a couple of eggs with “2.5-dev” as declared version.
I was not expecting to see version 2.5.1 tested, but indeed it is there

Max

**Comment by invemichele** [comment]
> You mean a separate badge or a third ‘panel’? 

this is what I had in mind:
![badges](https://user-images.githubusercontent.com/14904699/59508544-9f534900-8eae-11e9-95a4-f84461b08ad8.jpg)

if one is not providing the custom code via LOAD, then both the v2.5 and master badge will be red.

Another thing not related to custom code: for code compatible only with v2.6, I like the idea of keeping the red badge that shows v2.5 is failing, it might be useful to know and encourages people to update.

**Comment by GiovanniBussi** [comment]
So far I implemented this:
- v2.5 is not shown when user requires v2.6 (as suggested by reviewer).
- Green/red only reports on success/fail on travis.
- Additional badges are shown for custom code (version matches `*-mod`) and code using LOAD. This latter badges have no link currently.

See examples [here](https://www.plumed-nest.org/test-site/eggs/19/000/) and [here](https://www.plumed-nest.org/test-site/eggs/19/039/).

**Comment by GiovanniBussi** [comment]
@maxbonomi @carlocamilloni @gtribello let me know if this is ok to be merged

**Comment by maxbonomi** [comment]
Ok for me!

**Comment by carlocamilloni** [comment]
Yes

Sent from my iPhone

> Il giorno 14 giu 2019, alle ore 16:31, Massimiliano Bonomi <notifications@github.com> ha scritto:
> 
> Ok for me!
> 
> Sent from my iPhone
>

**Comment by GiovanniBussi** [comment]
I added an additional short page explaining the badges [here](https://www.plumed-nest.org/badges) (feel free to edit it). This page is reachable when you clock on those two special badges.

I consider this closed now.

**Comment by maxbonomi** [comment]
Not finding this page :-(

https://www.plumed-nest.org/badges

**Comment by GiovanniBussi** [comment]
@maxbonomi I think your last pushed overwrote mine for some reason (perhaps your build was slower and ended after even though it started earlier).

I guess it will be fixed with the next build.

**Comment by maxbonomi** [comment]
Ops, sorry

**Comment by maxbonomi** [comment]
It is online now, but looks weird :-(

https://www.plumed-nest.org/badges.md

**Comment by GiovanniBussi** [comment]
You should remove the `.md`.

I think I fixed right now the link from the badges.

**Comment by maxbonomi** [comment]
Yes, it is here

https://www.plumed-nest.org/badges.html
