### ISSUE TITLE
Egg 000 bad_alloc

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#71]
@invemichele could this be due to the fact that we declare 100000 atoms? Notice that we can customize this in the yml file. If in reality you have less atoms, we can put the correct number.

**Comment by invemichele** [comment]
By default my colvar uses all the atoms present, with `plumed.getAtoms().getNatoms()`, so this might be the issue!
In the example provided I use 250 atoms.

**Comment by invemichele** [comment]
it works!
https://www.plumed-nest.org/test-site/eggs/19/000/
