### ISSUE TITLE
`LOG-CLOSE` -> `LOG_CLOSE`

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#73]
@spiwokv you might have noticed that as of 2.6 we enforce usage of `LOG_CLOSE` instead of `LOG-CLOSE`. This is backward compatible with 2.5.

You might want to change the input files in [this egg](https://www.plumed-nest.org/eggs/19/047/) in order to have the green flag with both versions.

**Comment by maxbonomi** [comment]
I think he updated Materials Cloud archive a few days ago
but they are SUPER slow in uploading the new version
