### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#78]
@carlocamilloni I think there is an update of [this repo](https://github.com/carlocamilloni/papers-data/commits/master) that breaks one egg can you double check?

https://travis-ci.org/plumed-nest/plumed-nest/builds/598271284

**Comment by carlocamilloni** [comment]
Actually the commit should fix the egg (locally it works)

**Comment by maxbonomi** [comment]
Seems not to be working :-(

**Comment by carlocamilloni** [comment]
No actually I think my commit is more recent than latest nest update

Sent from my iPhone

> Il giorno 17 ott 2019, alle ore 18:16, Massimiliano Bonomi <notifications@github.com> ha scritto:
> 
> ﻿Seems not to be working :-(
> 
>

**Comment by carlocamilloni** [comment]
Sorry I see now, I’ll try to see what’s wrong
