### ISSUE TITLE
parallel simulations

### ISSUE THREAD

**Issue by maxbonomi** [plumed-nest/plumed-nest#8]
Many of the examples I would like to upload are replica-exchange like simulations (metainference) in which I need to test the input file in a mpi environment with N>1 istances

**Comment by GiovanniBussi** [comment]
I think MPI is available. The only problem is where to specify the number of replicas. I think it should be possible to customize it (different for each input file). The information could go together with the (optional) specification of the number of atoms (#7).

I think this stuff should go in the nest.yml file. We can decide a structure for that. I see it more difficult if people have to specify this information in the web form.

As a side note, consider that a large number of replicas could fail on travis.

**Comment by maxbonomi** [comment]
I can always test my metainference input with 1 replica / no MPI. The input will not change with N>1. I am just testing another type of simulation with the same input. In any case, if we really need to test the conditions in which the calculation was done, sometimes I will need to run on 128 replicas

**Comment by carlocamilloni** [comment]
I added an option in the yml parser for plumed_mpi, if true it runs the driver with mpiexec -np 2 and --multi 2. This is enough to make cases like weighted replica averaging and multiple walkers work. At the moment I added by and the flag in the nest.yml file of my egg. I am not sure about what is the best way to add this option in the contribute form, ideas?

**Comment by maxbonomi** [comment]
Shall we add a “radio” button to select between serial or parallel?

**Comment by carlocamilloni** [comment]
This is what I was thinking, but I thought that may be misleading in the sense that most of the applications are run in parallel but in practice mpi are not needed to test the validity of the syntax, in the end it is more something for us. An alternative may be that we test in scalar, if plumed driver fails we test also in parallel with replicas. 
Actually maybe this is the best solution

**Comment by GiovanniBussi** [comment]
Maybe should be "multi-replica" rather than parallel?

Should we allow to choose the number of replicas? I am not sure how many we
can ask on travis.

**Comment by carlocamilloni** [comment]
Again in terms of syntax 2 replicas are always enough as far as I know.

C

**Comment by carlocamilloni** [comment]
Do you think that running the failing cases twice could increase too much the builidngin time of the website?

**Comment by GiovanniBussi** [comment]
It could increase a bit because all the cases that are failing due to other
reasons will run twice. However, I think that already now the largest
amount of time is to download the zips, so probably it is not so important.

Notice that information should be provided "per input file" rather than
"per project", so it might be a bit more complicated to implement.

Why don't we run directly with 2 replicas?

**Comment by carlocamilloni** [comment]
Yes in principle we can run everything with two replicas, at some point I implemented it in this way but then I thought it was overkilling since this is needed only in few cases (essentially mine…)

C

**Comment by carlocamilloni** [comment]
Now is running everything with two replicas, I will check the time, if it is not too much
I will remove the unneeded code. Furthermore I think that the less stuff we ask in the contribute the better

**Comment by carlocamilloni** [comment]
Ok time is negligible, let’s run always with replicas

**Comment by GiovanniBussi** [comment]
Now that I closed #11 it is possible to see the stderr and stdout for each run. It is a bit annoying that they are duplicated.

If having files that require multiple replicas is considered "advanced", should we specify the number of replicas in the yml file (as Carlo implemented for number of atoms) and use one replica by default?

**Comment by carlocamilloni** [comment]
This is fine to me, we just need to document the advanced feature somewhere

**Comment by GiovanniBussi** [comment]
I think we can close this now
