### ISSUE TITLE
GitHub workflows

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed-nest/plumed-nest#82]
I made a test using GitHub workflows (see [this branch](https://github.com/plumed-nest/plumed-nest/blob/test-github-workflow/.github/workflows/main.yml)).

It looks slower than travis, but the timeout should be 6 hours here so it might be useful in the future.

I leave this issue here as a reference.

**Comment by GiovanniBussi** [comment]
See also [this](https://github.com/plumed/plumed2/issues/634).

**Comment by GiovanniBussi** [comment]
A fixed a few things in the test-github-workflow branch and made sure it produces the correct website pushing it on the test branch. I also enabled caching, which brings the time down to 26 min (compared with 15 min on travis, but perhaps it's the machine that is just slower, I think travis machines have 4 cores whereas Github machines have 2 cores).

Anyway, as soon as we want to (or need to) transition, we can do it.

**Comment by carlocamilloni** [comment]
I think it is time to move... on travis they say that now is a matter of weeks

**Comment by GiovanniBussi** [comment]
@carlocamilloni @maxbonomi @gtribello I am ready to merge. I pushed a couple of days ago the test site so that you should see [here](https://www.plumed-nest.org/test-site/) the site generated using GitHub Actions. I just pushed a new merge (that contains also Egg 21.016), it should be online less than a hour. You might want to double check as well.

If I don't hear anything, I will merge [this branch](https://github.com/plumed-nest/plumed-nest/blob/test-github-workflow/.github/workflows/main.yml) to master this afternoon.
