### ISSUE TITLE
Confirmation after egg submission

### ISSUE THREAD

**Issue by invemichele** [plumed-nest/plumed-nest#90]
It would be nice to have some sort of confirmation after the submission of an egg via the form. A small text note or a new screen saying something like "Your submission has been sent"

Now when you hit "submit" a new page opens with a google CAPTCHA, but after that you are redirected to the form page, with still all the fields compiled and it is not clear if the submission was successful or not (or at least it was not clear to me).
The email notification arrives (as it should) only some time after, when your submission is added to the nest.

**Comment by maxbonomi** [comment]
We will look into this. We are currently using the free version of Formspree to send the online form to the nest-email
(submission are then curated manually). The free version does not allow to redirect to a “thanks” page or send a confirmation email.
We would need to subscribe to the “Gold” version to enable this.

Max

**Comment by GiovanniBussi** [comment]
Could we switch to google form? I think they allow email notifications.

**Comment by invemichele** [comment]
Another simple solution could be adding a sentence just below the "submit" button that says something like "after completing the CAPTCHA your form is submitted. You will be notified via email as soon as your contribution appears in the nest"

**Comment by maxbonomi** [comment]
An even simpler solution is setting up an automatic reply using Gmail templates. We use plumed-nest@gmail.com as recipient of the Formspree form. I think it is easy to set up an automatic reply only in case of the first submission (not in case of replies to some requests sent from the person who is curating the submission via plumed-nest@gmail.com)
Max

**Comment by maxbonomi** [comment]
I simulated a submission, and after the CAPTCHA page I land on a page with:

Thanks!

The form was submitted successfully.


You don’t  see it?

Max

**Comment by invemichele** [comment]
ok, I tried again... and actually you are right! 
I got confused the first time because I didn't read and just clicked on the link to go back and once back the form was still fully compiled, as befor hitting "submit".
sorry, my bad :\

**Comment by maxbonomi** [comment]
In the meantime, I tried the automatic response using gmail to have a more personalized message. Sadly, gmail can reply to the sender (a no-reply formspree address) and not to the reply-to field (the actual contributor). Sad.
