### ISSUE TITLE
issues in visualizing paper links

### ISSUE THREAD

**Issue by invemichele** [plumed-nest/plumed-nest#91]
I just noticed that in some entries the link to the published article disappeared, see e.g. https://www.plumed-nest.org/eggs/19/068/
![Screenshot from 2021-04-27 10-00-16](https://user-images.githubusercontent.com/14904699/116206760-6be6d400-a73f-11eb-8754-157295525c23.png)

in others it is not correctly rendered, e.g. https://www.plumed-nest.org/eggs/20/015/
![Screenshot from 2021-04-27 10-02-25](https://user-images.githubusercontent.com/14904699/116206988-aea8ac00-a73f-11eb-837c-53a6144387a5.png)

and finally others look just fine

**Comment by maxbonomi** [comment]
Seems fine now :-(

**Comment by invemichele** [comment]
True! 🤷‍♂️
